# Server configuration
server.port=8080

# Gemini API Configuration
google.ai.api.key=AIzaSyD1q3p2yHe6RokwNJBYSIXRqC19K35NNDM
google.ai.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
